apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 80      # Expose port 80 externally
      targetPort: 8081  # Forward traffic to port 8081 inside the container
  type: LoadBalancer
